CREATE TABLE PRODUTOS 
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DESCRICAO VARCHAR(100) NOT NULL,
	QUANTIDADE REAL NOT NULL,
	PRECO REAL NOT NULL,
	CATEGORIAID INTEGER NOT NULL,
	FOREIGN KEY (CATEGORIAID) REFERENCES CATEGORIAS (ID)
)