INSERT INTO PRODUTOS (DESCRICAO, QUANTIDADE, PRECO, CATEGORIAID)
VALUES 
('QUEIJO', 100, 20.00, 1);

INSERT INTO PRODUTOS (DESCRICAO, QUANTIDADE, PRECO, CATEGORIAID)
VALUES 
('VINHO', 100, 50.00, 2);

INSERT INTO PRODUTOS (DESCRICAO, QUANTIDADE, PRECO, CATEGORIAID)
VALUES 
('TOMATE', 100, 10.00, 3);

INSERT INTO PRODUTOS (DESCRICAO, QUANTIDADE, PRECO, CATEGORIAID)
VALUES 
('ALFACE', 100, 4.00, 3);

INSERT INTO PRODUTOS (DESCRICAO, QUANTIDADE, PRECO, CATEGORIAID)
VALUES 
('CERVEJA', 100, 20.00, 2);

INSERT INTO PRODUTOS (DESCRICAO, QUANTIDADE, PRECO, CATEGORIAID)
VALUES 
('VODKA', 100, 100.00, 2);

INSERT INTO PRODUTOS (DESCRICAO, QUANTIDADE, PRECO, CATEGORIAID)
VALUES 
('ENERGETICO', 100, 30.00, 2);