BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "CLIENTES" (
	"ID"	INTEGER,
	"NOME"	VARCHAR(60) NOT NULL,
	"CPF"	VARCHAR(11) NOT NULL,
	"EMAIL"	VARCHAR(100) NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
INSERT INTO "CLIENTES" VALUES (1,'Joâo da Silva','09000152565','joao@email.com');
INSERT INTO "CLIENTES" VALUES (2,'Maria da Costa','09000152561','maria@email.com');
INSERT INTO "CLIENTES" VALUES (3,'José da Paz','09000152562','jose@email.com');
COMMIT;
