SELECT P.ID, P.PRECO, P.DESCRICAO PRODUTO, C.DESCRICAO CATEGORIA 
	FROM PRODUTOS P
	INNER JOIN CATEGORIAS C
		ON (P.CATEGORIAID = C.ID)
	WHERE P.ID = 1;
	
-- Testando colunas calculadas
SELECT P.ID, P.PRECO, P.DESCRICAO PRODUTO, C.DESCRICAO CATEGORIA, 
	(P.PRECO * P.QUANTIDADE) VALOR_TOTAL 
	FROM PRODUTOS P
	INNER JOIN CATEGORIAS C
		ON (P.CATEGORIAID = C.ID)
	WHERE P.ID = 1;

-- Testando Agrupamentos
SELECT C.DESCRICAO CATEGORIA, SUM(P.QUANTIDADE) QUANTIDADE
	FROM PRODUTOS P
	INNER JOIN CATEGORIAS C
		ON (P.CATEGORIAID = C.ID)
	GROUP BY C.ID;
	
-- Testando ordenação
SELECT P.DESCRICAO 
	FROM PRODUTOS P
	ORDER BY 1;	