CREATE TABLE ITENS_VENDAS 
(
	PRODUTOID INTEGER NOT NULL,
	VENDAID INTEGER NOT NULL,
	VALORPRODUTO REAL NOT NULL,
	DESCONTO REAL NOT NULL,
	FOREIGN KEY (PRODUTOID) REFERENCES PRODUTOS (ID),
	FOREIGN KEY (VENDAID) REFERENCES VENDAS (ID),
	PRIMARY KEY (PRODUTOID, VENDAID)
);

-- DROP TABLE ITENS_VENDAS;