INSERT INTO CATEGORIAS (DESCRICAO) VALUES 
('LATICINIOS');

INSERT INTO CATEGORIAS (DESCRICAO) VALUES 
('BEBIDAS');

INSERT INTO CATEGORIAS (DESCRICAO) VALUES 
('HORTIFRUTI');

INSERT INTO CATEGORIAS (DESCRICAO) VALUES 
('CARNES');